version: '3'

services:  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: parking01
      POSTGRES_USER: parking
      POSTGRES_DB: postegres

    ports:
      - "5432:5432"
